language: ruby
rvm:
  - jruby-18mode
  - jruby-19mode
  - jruby-9.0.5.0
  - jruby-9.1.8.0
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
before_install:
  - gem install bundler
script: bundle exec rake
gemfile: .travis.gemfile
